# Generated by Django 3.0.7 on 2020-06-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('display_size', models.FloatField()),
                ('cpu', models.CharField(max_length=32)),
                ('gpu', models.CharField(max_length=32)),
                ('ram_size', models.IntegerField()),
                ('rom_size', models.IntegerField()),
            ],
        ),
    ]
